package net.refriglobal.hvactools.ClasificacionListas


import android.view.animation.Animation
import android.view.animation.AnimationUtils
import java.util.ArrayList

class Listas_prueba {


    companion object
    {
        var listaPerdida: MutableList<ClasificasionListaPerdida>? = null
        var listaPPA: MutableList<List<ClasificacionListaPPA>>? = null
        var listaVelocidadPPA: List<List<ClasificacionListaVelocidad>>? = null
    }

    fun ListaPerdida() {
        listaPerdida = ArrayList()
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(0, 10.0))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(1, 9.0))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(2, 8.0))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(3, 7.0))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(4, 6.0))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(5, 5.0))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(6, 4.0))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(7, 3.5))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(8, 3.0))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(9, 2.5))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(10, 2.0))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(11, 1.5))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(12, 1.0))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(13, 0.9))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(14, 0.8))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(15, 0.7))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(16, 0.6))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(17, 0.5))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(18, 0.4))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(19, 0.35))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(20, 0.30))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(21, 0.25))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(22, 0.20))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(23, 0.15))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(24, 0.10))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(25, 0.09))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(26, 0.08))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(27, 0.07))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(28, 0.06))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(29, 0.05))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(30, 0.04))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(31, 0.035))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(32, 0.030))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(33, 0.025))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(34, 0.020))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(35, 0.015))
        (listaPerdida as ArrayList<ClasificasionListaPerdida>).add(ClasificasionListaPerdida(36, 0.010))
    }

    fun ListaPPA() {
        listaPPA = ArrayList()
        var listaDiametros: MutableList<ClasificacionListaPPA> = ArrayList()
        listaDiametros.add(ClasificacionListaPPA(1.5, 30, 10.00)) //Perdida: 10
        listaDiametros.add(ClasificacionListaPPA(1.5, 29, 9.00)) //Perdida: 9
        listaDiametros.add(ClasificacionListaPPA(1.5, 27, 8.00)) //Perdida: 8
        listaDiametros.add(ClasificacionListaPPA(1.5, 26, 7.00)) //Perdida: 7
        listaDiametros.add(ClasificacionListaPPA(1.5, 24, 6.00)) //Perdida: 6
        listaDiametros.add(ClasificacionListaPPA(1.5, 21, 5.00))
        listaDiametros.add(ClasificacionListaPPA(1.5, 19, 4.00))
        listaDiametros.add(ClasificacionListaPPA(1.5, 18, 3.50))
        listaDiametros.add(ClasificacionListaPPA(1.5, 16, 3.00))
        listaDiametros.add(ClasificacionListaPPA(1.5, 15, 2.50))
        listaDiametros.add(ClasificacionListaPPA(1.5, 13, 2.00))
        listaDiametros.add(ClasificacionListaPPA(1.5, 11, 1.50))
        listaDiametros.add(ClasificacionListaPPA(1.5, 10, 1.30))
        (listaPPA as ArrayList<List<ClasificacionListaPPA>>).add(listaDiametros)
        
        listaDiametros = ArrayList()
        listaDiametros.add(ClasificacionListaPPA(2.0, 66, 10.00))
        listaDiametros.add(ClasificacionListaPPA(2.0, 63, 9.00))
        listaDiametros.add(ClasificacionListaPPA(2.0, 59, 8.00))
        listaDiametros.add(ClasificacionListaPPA(2.0, 55, 7.00))
        listaDiametros.add(ClasificacionListaPPA(2.0, 51, 6.00))
        listaDiametros.add(ClasificacionListaPPA(2.0, 46, 5.00))
        listaDiametros.add(ClasificacionListaPPA(2.0, 41, 4.00))
        listaDiametros.add(ClasificacionListaPPA(2.0, 38, 3.50))
        listaDiametros.add(ClasificacionListaPPA(2.0, 35, 3.00))
        listaDiametros.add(ClasificacionListaPPA(2.0, 32, 2.50))
        listaDiametros.add(ClasificacionListaPPA(2.0, 28, 2.00))
        listaDiametros.add(ClasificacionListaPPA(2.0, 24, 1.50))
        listaDiametros.add(ClasificacionListaPPA(2.0, 19, 1.00))
        listaDiametros.add(ClasificacionListaPPA(2.0, 18, 0.90))
        listaDiametros.add(ClasificacionListaPPA(2.0, 17, 0.80))
        listaDiametros.add(ClasificacionListaPPA(2.0, 16, 0.70))
        listaDiametros.add(ClasificacionListaPPA(2.0, 15, 0.60))
        listaDiametros.add(ClasificacionListaPPA(2.0, 13, 0.50))
        listaDiametros.add(ClasificacionListaPPA(2.0, 12, 0.40))
        listaDiametros.add(ClasificacionListaPPA(2.0, 11, 0.35))
        (listaPPA as ArrayList<List<ClasificacionListaPPA>>).add(listaDiametros)

        listaDiametros = ArrayList()
        listaDiametros.add(ClasificacionListaPPA(3.0, 195, 10.00))
        listaDiametros.add(ClasificacionListaPPA(3.0, 188, 9.00))
        listaDiametros.add(ClasificacionListaPPA(3.0, 176, 8.00))
        listaDiametros.add(ClasificacionListaPPA(3.0, 163, 7.00))
        listaDiametros.add(ClasificacionListaPPA(3.0, 151, 6.00))
        listaDiametros.add(ClasificacionListaPPA(3.0, 136, 5.00))
        listaDiametros.add(ClasificacionListaPPA(3.0, 121, 4.00))
        listaDiametros.add(ClasificacionListaPPA(3.0, 113, 3.50))
        listaDiametros.add(ClasificacionListaPPA(3.0, 103, 3.00))
        listaDiametros.add(ClasificacionListaPPA(3.0, 94, 2.50))
        listaDiametros.add(ClasificacionListaPPA(3.0, 83, 2.00))
        listaDiametros.add(ClasificacionListaPPA(3.0, 71, 1.50))
        listaDiametros.add(ClasificacionListaPPA(3.0, 57, 1.00))
        listaDiametros.add(ClasificacionListaPPA(3.0, 54, 0.90))
        listaDiametros.add(ClasificacionListaPPA(3.0, 51, 0.80))
        listaDiametros.add(ClasificacionListaPPA(3.0, 47, 0.70))
        listaDiametros.add(ClasificacionListaPPA(3.0, 43, 0.60))
        listaDiametros.add(ClasificacionListaPPA(3.0, 39, 0.50))
        listaDiametros.add(ClasificacionListaPPA(3.0, 35, 0.40))
        listaDiametros.add(ClasificacionListaPPA(3.0, 32, 0.35))
        listaDiametros.add(ClasificacionListaPPA(3.0, 30, 0.30))
        listaDiametros.add(ClasificacionListaPPA(3.0, 27, 0.25))
        listaDiametros.add(ClasificacionListaPPA(3.0, 24, 0.20))
        listaDiametros.add(ClasificacionListaPPA(3.0, 21, 0.15))
        listaDiametros.add(ClasificacionListaPPA(3.0, 17, 0.10))
        listaDiametros.add(ClasificacionListaPPA(3.0, 16, 0.090))
        listaDiametros.add(ClasificacionListaPPA(3.0, 15, 0.080))
        listaDiametros.add(ClasificacionListaPPA(3.0, 14, 0.070))
        listaDiametros.add(ClasificacionListaPPA(3.0, 13, 0.060))
        listaDiametros.add(ClasificacionListaPPA(3.0, 12, 0.050))
        listaDiametros.add(ClasificacionListaPPA(3.0, 11, 0.040))
        (listaPPA as ArrayList<List<ClasificacionListaPPA>>).add(listaDiametros)

        listaDiametros = ArrayList()
        listaDiametros.add(ClasificacionListaPPA(4.0, 423, 10.00))
        listaDiametros.add(ClasificacionListaPPA(4.0, 405, 9.00))
        listaDiametros.add(ClasificacionListaPPA(4.0, 380, 8.00))
        listaDiametros.add(ClasificacionListaPPA(4.0, 352, 7.00))
        listaDiametros.add(ClasificacionListaPPA(4.0, 324, 6.00))
        listaDiametros.add(ClasificacionListaPPA(4.0, 294, 5.00))
        listaDiametros.add(ClasificacionListaPPA(4.0, 259, 4.00))
        listaDiametros.add(ClasificacionListaPPA(4.0, 241, 3.50))
        listaDiametros.add(ClasificacionListaPPA(4.0, 222, 3.00))
        listaDiametros.add(ClasificacionListaPPA(4.0, 201, 2.50))
        listaDiametros.add(ClasificacionListaPPA(4.0, 178, 2.00))
        listaDiametros.add(ClasificacionListaPPA(4.0, 152, 1.50))
        listaDiametros.add(ClasificacionListaPPA(4.0, 122, 1.00))
        listaDiametros.add(ClasificacionListaPPA(4.0, 115, 0.90))
        listaDiametros.add(ClasificacionListaPPA(4.0, 108, 0.80))
        listaDiametros.add(ClasificacionListaPPA(4.0, 101, 0.70))
        listaDiametros.add(ClasificacionListaPPA(4.0, 92, 0.60))
        listaDiametros.add(ClasificacionListaPPA(4.0, 84, 0.50))
        listaDiametros.add(ClasificacionListaPPA(4.0, 74, 0.40))
        listaDiametros.add(ClasificacionListaPPA(4.0, 69, 0.35))
        listaDiametros.add(ClasificacionListaPPA(4.0, 64, 0.30))
        listaDiametros.add(ClasificacionListaPPA(4.0, 58, 0.25))
        listaDiametros.add(ClasificacionListaPPA(4.0, 51, 0.20))
        listaDiametros.add(ClasificacionListaPPA(4.0, 44, 0.15))
        listaDiametros.add(ClasificacionListaPPA(4.0, 35, 0.10))
        listaDiametros.add(ClasificacionListaPPA(4.0, 33, 0.090))
        listaDiametros.add(ClasificacionListaPPA(4.0, 31, 0.080))
        listaDiametros.add(ClasificacionListaPPA(4.0, 28, 0.070))
        listaDiametros.add(ClasificacionListaPPA(4.0, 26, 0.060))
        listaDiametros.add(ClasificacionListaPPA(4.0, 24, 0.050))
        listaDiametros.add(ClasificacionListaPPA(4.0, 21, 0.040))
        listaDiametros.add(ClasificacionListaPPA(4.0, 19, 0.035))
        listaDiametros.add(ClasificacionListaPPA(4.0, 18, 0.030))
        listaDiametros.add(ClasificacionListaPPA(4.0, 16, 0.025))
        listaDiametros.add(ClasificacionListaPPA(4.0, 15, 0.020))
        listaDiametros.add(ClasificacionListaPPA(4.0, 12, 0.015))
        listaDiametros.add(ClasificacionListaPPA(4.0, 10, 0.010))
        (listaPPA as ArrayList<List<ClasificacionListaPPA>>).add(listaDiametros)
    }


}